<!DOCTYPE html>
<html>
<head>
    <title>Emergency SOS Alert</title>
</head>
<body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: #fff; padding: 20px; border-radius: 8px; border: 2px solid #EF4444; text-align: center;">
        <div style="background: #EF4444; color: white; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
            <h1 style="margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 2px;">🚨 EMERGENCY SOS ALERT 🚨</h1>
        </div>
        
        <p style="font-size: 18px; color: #1e293b; font-weight: bold; margin-bottom: 20px;">
            {{ $user->fullName }} has triggered an emergency SOS alert!
        </p>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 6px; text-align: left; margin-bottom: 20px;">
            <h3 style="margin-top: 0; color: #334155; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px;">User Details</h3>
            <p><strong>Name:</strong> {{ $user->fullName }}</p>
            <p><strong>Phone Number:</strong> {{ $user->contactNo }}</p>
            <p><strong>Email Address:</strong> {{ $user->userEmail }}</p>
            <p><strong>Address:</strong> {{ $user->address ?? 'Not provided' }}</p>
            
            @if($locationLink)
            <div style="margin-top: 15px; padding-top: 15px; border-top: 1px dashed #cbd5e1;">
                <p style="margin-bottom: 10px;"><strong>📍 Live Location (Approximate):</strong></p>
                <a href="{{ $locationLink }}" style="display: inline-block; background: #2563eb; color: white; text-decoration: none; padding: 10px 15px; border-radius: 4px; font-weight: bold;">View on Google Maps</a>
            </div>
            @endif
        </div>
        
        <p style="font-size: 16px; color: #EF4444; font-weight: bold;">
            Please try to contact them immediately. If they do not respond, consider contacting local authorities.
        </p>
        
        <div style="margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #94a3b8;">
            This is an automated emergency alert generated by the Nyayaprabha Women Safety Portal.
        </div>
    </div>
</body>
</html>
